export const GOOD = [
	'https://gph.is/11s0fCe',
	'https://gph.is/28UYagw',
	'https://gph.is/2fuwMbi',
	'https://gph.is/1examvU',
	'https://gph.is/19ZXH6L',
	'https://gph.is/2j4ML0A',
	'https://gph.is/2HFQz41',
	'https://gph.is/1nSBH7T',
	'https://gph.is/1izsKgy',
	'https://gph.is/1cTli7p',
	'https://gph.is/2wqgqYH',
	'https://gph.is/2oU9boe',
	'https://gph.is/1G0JKWk',
	'https://gph.is/179yPbz',
	'https://gph.is/2qrbQq3',
	'https://gph.is/2aHBxxB',
	'https://gph.is/2wBjpPO',
	'https://gph.is/1hCzx4v',
	'https://gph.is/1hCzx4v',
	'https://gph.is/1kw5oF6',
	'https://gph.is/2zThCH5',
	'https://gph.is/1ixVBSw',
	'https://gph.is/218REFN',
	'https://gph.is/2riflO1',
	'https://gph.is/2le8AeW',
	'https://gph.is/2rNzOxE',
	'https://gph.is/2y9Bky7',
	'https://gph.is/1NUYPIS',
	'https://gph.is/1l1j3VP',
	'https://gph.is/2yokRFq',
	'https://gph.is/2zFDODX',
	'https://gph.is/2RB4nAE',
	'https://gph.is/2GBvCGK',
	'https://gph.is/2GCtehH',
	'https://gph.is/2SsFlUL',
	'https://gph.is/2eYUD4y',
	'https://gph.is/19ljcLO',
	'https://gph.is/1rewpP9',
	'https://gph.is/1UOkDft',
	'https://gph.is/2cfUFmG',
	'https://gph.is/2g3nxfX',
	'https://gph.is/1Bgovhm',
	'https://gph.is/1PWJa1R',
	'https://gph.is/14nhF3B',
	'https://gph.is/2n642eL',
	'https://gph.is/2j6gpRi',
	'https://gph.is/2x02isX',
	'https://gph.is/1SK9E4W',
	'https://gph.is/2uuuyOh',
	'https://gph.is/1gTXuC8',
	'https://gph.is/2GuliyS',
	'https://gph.is/2BP20FH',
	'https://gph.is/17CTDsZ',
	'https://gph.is/18XotgB',
	'https://gph.is/KpWefJ',
	'https://gph.is/2vmyCAJ',
	'https://gph.is/YZrKla',
	'https://gph.is/2QUKtjM',
	'https://gph.is/1PWJa1R',
	'https://gph.is/1TL5s3R',
	'https://gph.is/2QUKtjM',
	'https://gph.is/1LgXBpe',
	'https://gph.is/129movC',
	'https://gph.is/1wWnRAY',
	'https://gph.is/1KmAoRg',
	'https://gph.is/1nLiiFG',
	'https://gph.is/1V75rbx',
	'https://gph.is/2pmQWrd',
	'https://gph.is/2wfb3Ny',
	'https://gph.is/1kTLU1x',
	'https://gph.is/2hdrhOw',
	'https://gph.is/2Ad8QDS',
	'https://gph.is/2pKSnAN'
];

export const BAD = [
	'https://gph.is/2IrX66n',
	'https://gph.is/2rNTBgi',
	'https://gph.is/1PGe5P9',
	'https://gph.is/1LaRgeN',
	'https://gph.is/13K9ldQ',
	'https://gph.is/28JmpPF',
	'https://gph.is/19KmETr',
	'https://gph.is/1dYxC6f',
	'https://gph.is/1izsKgy',
	'https://gph.is/2egQdlz',
	'https://gph.is/2bVDyCy',
	'https://gph.is/1EeH0Fb',
	'https://gph.is/1tVhNGF',
	'https://gph.is/2php8CZ',
	'https://gph.is/218REFN',
	'https://gph.is/1uEIQsP',
	'https://gph.is/1oSK90x',
	'https://gph.is/1ga6ssR',
	'https://gph.is/19ZswEv',
	'https://gph.is/1HwYgTS',
	'https://gph.is/19j0QdV',
	'https://gph.is/1pMIcY0',
	'https://gph.is/2hCqFAW',
	'https://gph.is/2gdmCfg',
	'https://gph.is/2CR6Q7U',
	'https://gph.is/2PSkE3i',
	'https://gph.is/1ncb1Nl',
	'https://gph.is/19VVPHs',
	'https://gph.is/1grIzly',
	'https://gph.is/1jTW2qL',
	'https://gph.is/1maAjIM',
	'https://gph.is/1GVuaZY',
	'https://gph.is/25GpZyg',
	'https://gph.is/28PE1ZU',
	'https://gph.is/15uCnUk',
	'https://gph.is/1RYf9Kw',
	'https://gph.is/1gxiZvH',
	'https://gph.is/2kccoPi',
	'https://gph.is/KpQfHA',
	'https://gph.is/2gnMVQb',
	'https://gph.is/2xcqIOA',
	'https://gph.is/2CN6fUB',
	'https://gph.is/2roBwHq',
	'https://gph.is/2iJla4M',
	'https://gph.is/1aacETd',
	'https://gph.is/2cTJRad',
	'https://gph.is/2p8a5xH',
	'https://gph.is/1rjAV43',
	'https://gph.is/1md4CSq',
	'https://gph.is/15AERAu',
	'https://gph.is/1GdjDrf',
	'https://gph.is/2ShgP9m',
	'https://gph.is/1am19GP',
	'https://gph.is/1L9a5zL',
	'https://gph.is/Z02Hib',
	'https://gph.is/2eedEOr',
	'https://gph.is/1sCg65F',
	'https://gph.is/1hywGHA',
	'https://gph.is/22XIsUu',
	'https://gph.is/1pGvX9P',
	'https://gph.is/2xw1J6V',
	'https://gph.is/2pnvyjS',
	'https://gph.is/1xiPms8',
	'https://gph.is/1dO2OGq',
	'https://gph.is/1ODqq6c',
	'https://gph.is/2cRDWEW',
	'https://gph.is/1afwrT8',
	'https://gph.is/1skUuZ0',
	'https://gph.is/12PlNxP',
	'https://gph.is/2fuLWNy',
	'https://gph.is/1tlfqlP',
	'https://gph.is/1USYN6v',
	'https://gph.is/1IRCxHa',
	'https://gph.is/OkBCbc',
	'https://gph.is/2yi7rf8',
	'https://gph.is/194z6hO',
	'https://gph.is/2y6eTbk'
];

export const GOODLOCAL = [
	'200 (2).gif',
	'200 (3).gif',
	'200 (4).gif',
	'200 (5).gif',
	'200 (6).gif',
	'200 (7).gif',
	'200.gif',
	'giphy (1).gif',
	'giphy (10).gif',
	'giphy (11).gif',
	'giphy (12).gif',
	'giphy (13).gif',
	'giphy (14).gif',
	'giphy (15).gif',
	'giphy (16).gif',
	'giphy (17).gif',
	'giphy (18).gif',
	'giphy (19).gif',
	'giphy (2).gif',
	'giphy (20).gif',
	'giphy (21).gif',
	'giphy (22).gif',
	'giphy (23).gif',
	'giphy (24).gif',
	'giphy (25).gif',
	'giphy (26).gif',
	'giphy (27).gif',
	'giphy (28).gif',
	'giphy (29).gif',
	'giphy (3).gif',
	'giphy (30).gif',
	'giphy (31).gif',
	'giphy (32).gif',
	'giphy (33).gif',
	'giphy (34).gif',
	'giphy (35).gif',
	'giphy (36).gif',
	'giphy (37).gif',
	'giphy (38).gif',
	'giphy (39).gif',
	'giphy (4).gif',
	'giphy (40).gif',
	'giphy (41).gif',
	'giphy (42).gif',
	'giphy (43).gif',
	'giphy (44).gif',
	'giphy (45).gif',
	'giphy (46).gif',
	'giphy (47).gif',
	'giphy (48).gif',
	'giphy (49).gif',
	'giphy (5).gif',
	'giphy (50).gif',
	'giphy (51).gif',
	'giphy (52).gif',
	'giphy (53).gif',
	'giphy (54).gif',
	'giphy (55).gif',
	'giphy (56).gif',
	'giphy (57).gif',
	'giphy (6).gif',
	'giphy (7).gif',
	'giphy (8).gif',
	'giphy (9).gif',
	'giphy-downsized-large (1).gif',
	'giphy-downsized-large (2).gif',
	'giphy-downsized-large (3).gif',
	'giphy-downsized-large (4).gif',
	'giphy-downsized-large (5).gif',
	'giphy-downsized-large (6).gif',
	'giphy-downsized-large.gif',
	'giphy.gif'
];

export const BADLOCAL = [
	'200 (1).gif',
	'200 (10).gif',
	'200 (11).gif',
	'200 (12).gif',
	'200 (13).gif',
	'200 (14).gif',
	'200 (15).gif',
	'200 (16).gif',
	'200 (17).gif',
	'200 (18).gif',
	'200 (2).gif',
	'200 (3).gif',
	'200 (4).gif',
	'200 (5).gif',
	'200 (6).gif',
	'200 (7).gif',
	'200 (8).gif',
	'200 (9).gif',
	'200.gif',
	'200w.gif',
	'giphy (1).gif',
	'giphy (10).gif',
	'giphy (11).gif',
	'giphy (12).gif',
	'giphy (13).gif',
	'giphy (14).gif',
	'giphy (15).gif',
	'giphy (16).gif',
	'giphy (17).gif',
	'giphy (18).gif',
	'giphy (19).gif',
	'giphy (2).gif',
	'giphy (20).gif',
	'giphy (21).gif',
	'giphy (22).gif',
	'giphy (23).gif',
	'giphy (24).gif',
	'giphy (25).gif',
	'giphy (26).gif',
	'giphy (27).gif',
	'giphy (28).gif',
	'giphy (29).gif',
	'giphy (3).gif',
	'giphy (30).gif',
	'giphy (31).gif',
	'giphy (32).gif',
	'giphy (33).gif',
	'giphy (34).gif',
	'giphy (35).gif',
	'giphy (36).gif',
	'giphy (37).gif',
	'giphy (38).gif',
	'giphy (39).gif',
	'giphy (4).gif',
	'giphy (40).gif',
	'giphy (41).gif',
	'giphy (42).gif',
	'giphy (43).gif',
	'giphy (44).gif',
	'giphy (45).gif',
	'giphy (46).gif',
	'giphy (47).gif',
	'giphy (48).gif',
	'giphy (49).gif',
	'giphy (5).gif',
	'giphy (50).gif',
	'giphy (51).gif',
	'giphy (52).gif',
	'giphy (53).gif',
	'giphy (54).gif',
	'giphy (6).gif',
	'giphy (7).gif',
	'giphy (8).gif',
	'giphy (9).gif',
	'giphy-downsized-large (1).gif',
	'giphy-downsized-large (2).gif',
	'giphy-downsized-large.gif',
	'giphy.gif'
];
